# Generated by Django 4.2.1 on 2023-05-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0003_alter_customuser_custom_groups_and_more"),
    ]

    operations = [
        migrations.DeleteModel(name="CustomUser",),
    ]
