# Generated by Django 4.2.1 on 2023-05-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0005_employe"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="adress",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="client",
            name="date_naissance",
            field=models.DateField(blank=True, null=True),
        ),
    ]
