# Generated by Django 4.2.1 on 2023-05-26 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0006_client_adress_client_date_naissance"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="telphone",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
