# Generated by Django 4.2.1 on 2023-05-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0007_client_telphone"),
    ]

    operations = [
        migrations.AddField(
            model_name="employe",
            name="dateembauche",
            field=models.DateField(blank=True, null=True),
        ),
    ]
