# Generated by Django 4.2.1 on 2023-05-27 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0008_employe_dateembauche"),
    ]

    operations = [
        migrations.CreateModel(
            name="vechule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("immatriculation", models.CharField(max_length=30)),
                ("modele", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=30)),
                ("puissance", models.CharField(max_length=30)),
                ("livraison", models.DateField(blank=True, null=True)),
                ("fin_liv", models.DateField(blank=True, null=True)),
                ("km", models.CharField(max_length=100)),
                ("gam", models.CharField(max_length=100)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pfm.client",
                    ),
                ),
            ],
        ),
    ]
