# Generated by Django 4.2.1 on 2023-06-07 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0010_client_gender_employe_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemplacementVehicule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vechuletype", models.CharField(max_length=30)),
                ("issuetype", models.CharField(max_length=50)),
                ("pichupdate", models.DateField(blank=True, null=True)),
                ("gam", models.CharField(blank=True, max_length=40, null=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pfm.client",
                    ),
                ),
                (
                    "vechule",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pfm.vechule",
                    ),
                ),
            ],
        ),
    ]
