# Generated by Django 4.2.1 on 2023-06-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0011_remplacementvehicule"),
    ]

    operations = [
        migrations.AddField(
            model_name="remplacementvehicule",
            name="status",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
