# Generated by Django 4.2.1 on 2023-06-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0012_remplacementvehicule_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vechule",
            name="age",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
