# Generated by Django 4.2.1 on 2023-06-10 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0013_vechule_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="remplacementvehicule",
            name="Description",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="remplacementvehicule",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="remplacementvehicule",
            name="dateincident",
            field=models.CharField(blank=True, max_length=1000000000000, null=True),
        ),
        migrations.AddField(
            model_name="remplacementvehicule",
            name="lieu_incident",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="remplacementvehicule",
            name="requests",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name="remplacementvehicule",
            name="type_de_reparation",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name="remplacementvehicule",
            name="issuetype",
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
