# Generated by Django 4.2.1 on 2023-06-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0015_remplacementvehicules_delete_remplacementvehicule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remplacementvehicules",
            name="issuetype",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
