# Generated by Django 4.2.1 on 2023-06-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0017_rename_requests_remplacementvehicules_otherrequests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remplacementvehicules",
            name="otherrequests",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
