# Generated by Django 4.2.1 on 2023-06-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0018_alter_remplacementvehicules_otherrequests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="remplacementvehicules",
            name="Description",
            field=models.CharField(blank=True, max_length=1000000000000, null=True),
        ),
        migrations.AlterField(
            model_name="remplacementvehicules",
            name="dateincident",
            field=models.DateField(blank=True, null=True),
        ),
    ]
