# Generated by Django 4.2.1 on 2023-06-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0022_remove_vechule_age_vechule_date_naiss"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vechule",
            name="date_naiss",
            field=models.DateField(blank=True, null=True),
        ),
    ]
