# Generated by Django 4.2.1 on 2023-06-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0023_alter_vechule_date_naiss"),
    ]

    operations = [
        migrations.AddField(
            model_name="vechule",
            name="cas",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
