# Generated by Django 4.2.1 on 2023-06-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0025_remplacementvechule_historique"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="is_user_authenticated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="employe",
            name="is_user_authenticated",
            field=models.BooleanField(default=False),
        ),
    ]
