# Generated by Django 4.2.1 on 2023-06-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0026_client_is_user_authenticated_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="is_user_authenticated",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="employe",
            name="is_user_authenticated",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
