# Generated by Django 4.2.1 on 2023-06-18 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pfm", "0028_client_last_activity_employe_last_activity"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="employe",
            name="creation_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
